### ISSUE TITLE
SASL authentication should error immediately if services are absent

### ISSUE THREAD

**Issue by ghost** [shalture/thelfylda#1]
I'm not sure exactly how this could be implemented, but @kaniini brought it up on IRC so I thought I'd open an issue.

**Comment by maxteufel** [comment]
I have two ideas for this:
1. Add an ENCAP command so linked services can announce that they can do SASL. The IRCd remembers that until the server unlinks. If there's no server reporting that it can do SASL, stop authentication.
2. Check for U:lined servers. If no U:lined servers are linked, stop authentication.

1 would require services with SASL support to add that ENCAP command, 2 would still time out when none of these servers can do SASL.

**Comment by kaniini** [comment]
The solution is to have it check for SaslServ presence.

**Comment by maxteufel** [comment]
@kaniini That's the easiest solution but simply fails when SaslServ has a different nick.

**Comment by kaniini** [comment]
You make it a configuration option...

**Comment by maxteufel** [comment]
I'll look into that and submit a pull request when it's ready.

**Comment by jlu5** [comment]
What about other services packages providing SASL?

**Comment by kaniini** [comment]
In TS6, SASL messages are routed to a specific UID.  Thusly, you make it a configuration option.  On other services which do not have a special UID for it, you would set NickServ as the agent.

**Comment by maxteufel** [comment]
See zohlai/neephi@91b0ced.

**Comment by ghost** [comment]
~~Why have the nick of SaslServ defined twice instead of using the existing option?~~

Never mind, that's defined in the services config, not the IRCd config.

**Comment by kaniini** [comment]
@maxanton that's a good start, but an optimization you can do is immediately route the SASL request to that UID, thus bypassing a discovery request.  might as well do that too...

**Comment by maxteufel** [comment]
~~@kaniini how would a server admin get SaslServ's UID (in Atheme & forks)? Is it static?~~

nevermind, misread that.

**Comment by ghost** [comment]
@ilbelkyr Any plans on ~~merging~~ cherry-picking https://github.com/zohlai/neephi/commit/782fb0a7b8a8aeb872e97c6e529767fa4ac3ce26?

**Comment by maxteufel** [comment]
I guess you ~~want~~ need zohlai/neephi@91b0ced too if you need that commit; zohlai/neephi@782fb0a doesn't add any config parsing code for `saslservnick`.

**Comment by ghost** [comment]
True, I missed that.

**Comment by ilbelkyr** [comment]
I'm not focusing on IRCd things very much for the time being, but yeah, can do.
